### ISSUE TITLE
Editing the email text area background color independently

### ISSUE THREAD

**Issue by bomanimc** [nylas/N1-theme-starter#1]
Hi,

I'm working on a new email theme, and I want to have a black background for the email page, but a white background for the area that contains the actual email content. Currently, I set the background-primary to black so that the list items can be black in the inbox tables. This color seems to persist to the text area for emails too, which causes some issues when people use specifically black text for their text.

<img width="1440" alt="screen shot 2016-06-12 at 7 31 08 pm" src="https://cloud.githubusercontent.com/assets/6589909/15995760/fb0ae1f8-30d4-11e6-877c-b8cb6a233ab7.png">

As you can see highlighted towards the bottom of the page, there's some black text that you can't see because the background of the text area is black. 

Is there a way for me to change the background of the email text area to white, while leaving the inbox email tables black (as shown below)?  Here's my fork: https://github.com/bomanimc/N1-theme-starter

<img width="1440" alt="screen shot 2016-06-12 at 7 42 36 pm" src="https://cloud.githubusercontent.com/assets/6589909/15995842/de1cfc74-30d5-11e6-897d-526480261537.png">

**Comment by jackiehluo** [comment]
Hey! Unfortunately, that's a problem we had with our dark theme—it's not super easy to deal with the email frame because we can't control the colors of the email body or background. [Here's](https://github.com/nylas/N1/blob/master/internal_packages/ui-dark/styles/email-frame.less) how we addressed it. Let me know if that helps!

**Comment by bomanimc** [comment]
Thanks for the response @jackiehluo! Could you explain a bit about what this code does?

**Comment by jackiehluo** [comment]
@bomanimc It inverts the colors in the frame!

**Comment by bomanimc** [comment]
Here's a snip from the current dark theme:
<img width="597" alt="screen shot 2016-06-13 at 6 14 15 pm" src="https://cloud.githubusercontent.com/assets/6589909/16028280/a7360c2e-3192-11e6-98c9-3c0b4ad6addc.png">

@jackiehluo Using the Dark theme, I still notice that the email frame has a dark background. Is there anyway to independently change the color of the email frame?

My goal would be to independently change the background color of that area where the text lies to white. Is that possible? Sorry if I'm not fully understanding everything you've mentioned so far!

**Comment by jackiehluo** [comment]
@bomanimc That Dark theme is out of date! There are changes coming in the next update.

And unfortunately, it's really difficult to just change the text to white. If the text there is black, it means that the style has been hardcoded into the email body, and (as far as I know) you would have to parse the HTML and change the colors—without easily telling what colors they are. The only reliable way to deal with it is inverting the email body colors.

**Comment by bomanimc** [comment]
Totally agreed about how difficult it'd be to try to change all of that stuff. I dropped that email-frame.less snippet into my project (in the styles directory of imported theme in .nylas/packages/) and refreshed/restarted, but I don't see any changes. Does that snippet work with the current version of Nylas, or do I need to wait for the next update for it be able to have an effect on the styling?

**Comment by jackiehluo** [comment]
@bomanimc It should work! You might need to list it in your `package.json` so that N1 knows to look for it.

**Comment by bomanimc** [comment]
Thanks! It all works. I appreciate it!
